language: dlang
install:
 - sudo wget http://netcologne.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
 - sudo apt-get update
 - sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring
 - sudo apt-get update
 - sudo apt-get -y install dmd-bin dub
 - gem install cucumber
 - git clone https://github.com/atilaneves/unit-threaded.git
 - git clone https://github.com/atilaneves/dtest.git
 - git clone https://github.com/atilaneves/cerealed.git
 - cd dtest
 - dub build
 - cd ..
 - dub build --build=release
script:
 - dtest/dtest -u unit-threaded -I cerealed
 - cucumber
